+incdir+${PROJECT_DIR}/modules/cva6/core/include
+incdir+${PROJECT_DIR}/fpu_common
+incdir+${PROJECT_DIR}/modules/cva6/core/cvfpu/src
+incdir+${PROJECT_DIR}/modules/cva6/vendor/pulp-platform/common_cells/src
${PROJECT_DIR}/modules/cva6/core/include/config_pkg.sv
${PROJECT_DIR}/fpu_common/cv64a60ax_config_pkg.sv
${PROJECT_DIR}/modules/cva6/core/include/riscv_pkg.sv
${PROJECT_DIR}/modules/cva6/core/include/build_config_pkg.sv
${PROJECT_DIR}/modules/cva6/core/include/ariane_pkg.sv
${PROJECT_DIR}/modules/cva6/core/cvfpu/src/fpnew_pkg.sv
${PROJECT_DIR}/modules/cva6/vendor/pulp-platform/common_cells/src/lfsr.sv
${PROJECT_DIR}/modules/cva6/vendor/pulp-platform/common_cells/src/cf_math_pkg.sv
${PROJECT_DIR}/modules/cva6/vendor/pulp-platform/common_cells/src/lzc.sv
${PROJECT_DIR}/modules/cva6/vendor/pulp-platform/common_cells/src/rr_arb_tree.sv
${PROJECT_DIR}/fpu_common/fpu_common_pkg.sv
+incdir+${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/clk/rtl
+incdir+${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl
+incdir+${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl
+incdir+${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl
${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/clk/rtl/gated_clk_cell.v
${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ctrl.v
${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ff1.v
${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_pack_single.v
${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_prepare.v
${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_round_single.v
${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_special.v
${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_srt_single.v
${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_top.v
${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_dp.v
${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_frbus.v
${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_src_type.v
${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_ctrl.v
${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_double.v
${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_ff1.v
${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_pack.v
${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_prepare.v
${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_round.v
${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_scalar_dp.v
${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_bound_table.v
${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_with_sqrt.v
${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt.v
${PROJECT_DIR}/modules/cva6/core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_top.v
+incdir+${PROJECT_DIR}/modules/cva6/vendor/pulp-platform/common_cells/include
+incdir+${PROJECT_DIR}/modules/cva6/core/cvfpu/src
+incdir+${PROJECT_DIR}/modules/cva6/core/cvfpu/src/fpu_div_sqrt_mvp/hdl
+incdir+${PROJECT_DIR}/modules/cva6/core
${PROJECT_DIR}/modules/cva6/core/cvfpu/src/fpnew_cast_multi.sv
${PROJECT_DIR}/modules/cva6/core/cvfpu/src/fpnew_classifier.sv
${PROJECT_DIR}/modules/cva6/core/cvfpu/src/fpnew_divsqrt_th_32.sv
${PROJECT_DIR}/modules/cva6/core/cvfpu/src/fpnew_divsqrt_th_64_multi.sv
${PROJECT_DIR}/modules/cva6/core/cvfpu/src/fpnew_divsqrt_multi.sv
${PROJECT_DIR}/modules/cva6/core/cvfpu/src/fpnew_fma_multi.sv
${PROJECT_DIR}/modules/cva6/core/cvfpu/src/fpnew_fma.sv
${PROJECT_DIR}/modules/cva6/core/cvfpu/src/fpnew_noncomp.sv
${PROJECT_DIR}/modules/cva6/core/cvfpu/src/fpnew_opgroup_block.sv
${PROJECT_DIR}/modules/cva6/core/cvfpu/src/fpnew_opgroup_fmt_slice.sv
${PROJECT_DIR}/modules/cva6/core/cvfpu/src/fpnew_opgroup_multifmt_slice.sv
${PROJECT_DIR}/modules/cva6/core/cvfpu/src/fpnew_rounding.sv
${PROJECT_DIR}/modules/cva6/core/cvfpu/src/fpnew_top.sv
${PROJECT_DIR}/modules/cva6/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv
${PROJECT_DIR}/modules/cva6/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/control_mvp.sv
${PROJECT_DIR}/modules/cva6/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv
${PROJECT_DIR}/modules/cva6/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv
${PROJECT_DIR}/modules/cva6/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv
${PROJECT_DIR}/modules/cva6/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv
${PROJECT_DIR}/modules/cva6/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv
${PROJECT_DIR}/modules/cva6/core/fpu_wrap.sv
+incdir+${PROJECT_DIR}
+incdir+${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/memory_partition
+incdir+${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/memory_partition
+incdir+${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/reset_gen
+incdir+${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/watchdog
+incdir+${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/clock_gen
+incdir+${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/unix_utils
+incdir+${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/pulse_gen
+incdir+${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/bp_gen
+incdir+${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/generic_agent
+incdir+${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/memory_rsp_model
+incdir+${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/memory_rsp_model/axi2mem
+incdir+${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/memory_shadow
+incdir+${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/clock_mon
+incdir+${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/perf_mon
${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/memory_partition/memory_partitions_pkg.sv
${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/reset_gen/reset_vif_xrtl_pkg.sv
${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/reset_gen/xrtl_reset_vif.sv
${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/reset_gen/reset_driver_pkg.sv
${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/watchdog/watchdog_pkg.sv
${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/clock_gen/xrtl_clock_vif.sv
${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/clock_gen/clock_vif_xrtl_pkg.sv
${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/clock_gen/clock_driver_pkg.sv
${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/unix_utils/unix_utils_pkg.sv
${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/pulse_gen/pulse_if.sv
${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/pulse_gen/pulse_gen_pkg.sv
${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/bp_gen/bp_vif_xrtl_pkg.sv
${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/bp_gen/bp_driver_pkg.sv
${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/bp_gen/bp_vif.sv
${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/generic_agent/generic_agent_pkg.sv
${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/generic_agent/generic_if.sv
${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/memory_rsp_model/memory_response_model_pkg.sv
${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/memory_rsp_model/memory_response_if.sv
${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/memory_rsp_model/axi2mem/axi2mem_pkg.sv
${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/memory_rsp_model/axi2mem/axi_intf.sv
${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/memory_shadow/memory_shadow_pkg.sv
${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/clock_mon/xrtl_clock_mon_vif.sv
${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/clock_mon/clock_mon_vif_xrtl_pkg.sv
${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/clock_mon/clock_monitor_pkg.sv
${PROJECT_DIR}/modules/core-v-verif/lib/cv_dv_utils/uvm/perf_mon/perf_mon_pkg.sv
+incdir+${PROJECT_DIR}/fpu_agent
${PROJECT_DIR}/fpu_agent/fpu_agent_pkg.sv
${PROJECT_DIR}/fpu_agent/fpu_if.sv
+incdir+${PROJECT_DIR}/ref_model_csim/rtl
${PROJECT_DIR}/ref_model_csim/rtl/fpu_refmodel_pkg.sv
+incdir+${PROJECT_DIR}/env
${PROJECT_DIR}/env/fpu_env_pkg.sv
+incdir+${PROJECT_DIR}/tests
${PROJECT_DIR}/tests/fpu_test_pkg.sv
${PROJECT_DIR}/top/rtl/tb_top.sv

